### ISSUE TITLE
MK3S + raspberry

### ISSUE THREAD

**Issue by michalmichalcz** [prusa3d/Prusa-Link-Web#107]
Hi can i this install to my RPI 3B+ and use Prusa i3 mk3s?

**Comment by ondratu** [comment]
Hi, this repository is for all our printers Web interface only. When you want to be betatester of our solution, please use this form https://docs.google.com/forms/d/10LpN7LGAlbZwMCPpBXFTeOMij3mXJ77acBu46k_aO-4/edit?ts=60632f0b

**Comment by michalmichalcz** [comment]
Tyvm
