### ISSUE TITLE
Setup error: "Can't connect to Prusa Connect."

### ISSUE THREAD

**Issue by mathieucarbou** [prusa3d/Prusa-Link-Web#198]
This is a copy of https://forum.prusa3d.com/forum/bugs-errors/error-cant-connect-to-prusa-connect/#post-611598 with more info.

![](https://forum.prusa3d.com/wp-content/uploads/2022/06/Screenshot-2022-06-27-at-00.37.18.png)

I I can SSH into the device and I can reach the host though...

```shell
pi@prusa:~ $ nc -v -z connect.prusa3d.com 443
Connection to connect.prusa3d.com (172.104.231.244) 443 port [tcp/https] succeeded!
```

* I have the latest firmware: prusa3d_fw_3_11_0_MK3S
* Printer: Original Prusa i3 MK3S+
* Raspberry Pi Zero W running PrusaLink downloaded from the link at the official page here: https://help.prusa3d.com/guide/prusalink-and-prusa-connect-setup-for-mk3-s-_221744
* Image version is 0.6.1

Please see attached logs from: `prusa-link -f -d start`: [debug.log](https://github.com/prusa3d/Prusa-Link-Web/files/8987708/debug.log)

creds used were:

admin
12345678

Note:I tested with and without 2FA on my account.

**Comment by Prusa-Support** [comment]
Thanks for reaching us.

Apparently, there is a problem with connecting Prusa Link to Prusa Connect.
Some reasons for the problem could be, for example:
- problem with DNS;
- some PROXY on the way;
- some other (IP routing) problem;

and more...

We are working on explanatory error messages, which will be implemented in the next update (coming soon).
You can try reviewing one of the listed examples of issues, or please wait for the next version.
Thanks for your patience.

Michele Moramarco
Prusa Research

**Comment by ondratu** [comment]
Is that error still current? Can we close this issue? @mathieucarbou

**Comment by mathieucarbou** [comment]
Yes we can close.

**Comment by Prusa-Support** [comment]
Thank you for your cooperation and I'll close this issue now.
