### ISSUE TITLE
[FEATURE REQUEST] Allow file rewrite for PrusaLink uploads

### ISSUE THREAD

**Issue by jkavalik** [prusa3d/Prusa-Link-Web#232]
When I try to reupload a file that already exists on the flashdrive, I currently get an error (403 iirc?). PrusaLink on MK3+RPi does not do that and rewrites the file instead. I find that very useful because it allows me to restart prints (after first-layer problems etc.) by just re-"upload and print" directly from PrusaSlicer instead of opening the PrusaLink in a browser and searching for the right file to start.

So would it be please possible to implement that on the Mini too?
- automatically rewrite already existing file if a file with the same name is uploaded.

**Comment by ondratu** [comment]
We plan to do that. That is about API improvement first. So stay tuned, that will comes.

**Comment by stefanct** [comment]
There has been a lot work done on the PL API in the last months. If this feature still require some more work maybe it would make sense to default to overwrite it (without choice) for now. That should be rather trivial to implement and an improvement for pretty much all users (I seriously doubt anybody relies on the printer to not overwrite gcode exports, at least I'd hope so ;)

**Comment by DaReaLDeviL** [comment]
Please change that like requestet. I whould like that also and it is not the best way to always login in the printer. Another thumps up for this feature!
