### ISSUE TITLE
[ENHANCEMENT] <Prusalink - display more values from printer>

### ISSUE THREAD

**Issue by Eldenroot** [prusa3d/Prusa-Link-Web#274]
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - [MINI+]
**Optional upgrades** - [Filament Runout Sensor]

**Is your suggested improvement related to an existing problem? Please describe.**
  Prusalink - I would like to see more info from the printer - for example values - fan speeds, bed type, material of filament type etc.

**Describe the expected functionality**
  Add more info from printer in Prusalink

**Comment by Prusa-Support** [comment]
Thanks again for sharing ideas.
I believe that the implementation of further status/informative data is already in the plans for Prusa Link or Prusa Connect (not compatible with Prusa MINI yet).
Your suggestions are appreciated.

Michele Moramarco
Prusa Research

**Comment by ondratu** [comment]
Hi, thanks a lot.

All values you want to see is available in Connect. PrusaLink is light web on printer side, but PrusaConnect is much complex system. At this moment, we are working on new firmware version, which allows link MINI to PrusaConnect.

**Comment by sbierly** [comment]
Seconding this *old* request. For goodness sakes, Prusa you are a big company now and this is dirt simple stuff. If you are going to roll out something like this, please make it more functional, less buggy, and absolutely you should be supporting all or none of your printers with this, or anything else.

**Comment by Prusa-Support** [comment]
There has been big news at an intense and growing rate in the last two years.
Have a look at the [featured blog posts](https://blog.prusa3d.com/category/featured_8/) to get an insight into the main announced projects.
It goes without saying that this is just scratching the surface.

There is a huge teamwork behind this but we really know there is always room to improve. In fact, the company keeps on expanding at a fast pace.

Back to the issue now.
We are aware of the current limitations so please bear with us while we are working on this.
For open discussions, please pay a visit to our [forum](https://forum.prusa3d.com/).

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
Prusa Connect is up and running! 🎉 
With the new firmware now available in alpha version (potentially unstable), the printer Prusa MINI is enabled on Prusa Connect too.

Prusa Connect, at the current non-final stage (beta), already includes useful data and details from the printer and the print files.
Prusa Link, as of now, is expected to remain the most basic possible interface, as it is hosted on the printer's board, and it acts as a bridge between the printer and Prusa Connect.

![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/103262060/0548da57-1b4c-42f0-b768-f6f6e46e7822)
![image](https://github.com/prusa3d/Prusa-Link-Web/assets/103262060/f827f1f2-64f7-4efb-be1b-0c50226d7bb5)

Please allow me to close this issue as solved but feel free to share feedback below.

Michele Moramarco
Prusa Research

**Comment by sbierly** [comment]
alpha version = not solved
--Scott

**Comment by twshield** [comment]
It would be nice if the PrusaLink web interface showed the type of filament (PLA, PETG, etc) that is loaded.  This was displayed on the old pre-PrusaLink interface.

**Comment by ondratu** [comment]
@twshield will be in next firmware

**Comment by jhaand** [comment]
If Prusalink is the only locally supported interface, then Prusalink should also provide status updates on the used filament and current printing status. This will also allow for a nice integration with Home-Assistant as the locally served monitoring solution. 

I was quite disappointed that I still have to check manually for color changes. Prusalink showed the status as `printing` while my Prusa Mini was parked for a color change.
