### ISSUE TITLE
[FEATURE REQUEST] MMU2S Support.

### ISSUE THREAD

**Issue by dameningen4914** [prusa3d/Prusa-Link-Web#292]
Please support MMU2S. 
My MMU2S works well, but prusalink is not support mmu2s yet.

**Comment by Prusa-Support** [comment]
Yes, I'm sorry, the Multi Material functionality is not supported yet.
More products will be supported in the future.
Our developers are tirelessly working on this.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment]
This issue will be closed as a duplicate of https://github.com/prusa3d/Prusa-Link-Web/issues/255.

Michele Moramarco
Prusa Research
