### ISSUE TITLE
Z Height in Prusa Link is steadily jumping with values beyond layer height

### ISSUE THREAD

**Issue by KlausKraemer** [prusa3d/Prusa-Link-Web#312]
I feel it is a bug, because how can "Z Height" jump every second for up to half a millimeter?

Just now on the same layer Z Height jumps wildly between 1.2 and 0.7 mm. I am just printing with a 0.15 mm layer height!

As this information seems to be unreliable, why not also display the layer number? Which should really be stable ...

**Comment by TojikCZ** [comment]
Yup, the Z height is influenced by the Mesh Bed Leveling correction and Z-Hop. So the Z height really is fluctuating during printing. We get that you'd be more interested in height in the model vs the Marlin's internal Z height. But this feature would depend on the slicer used as it would need to leave some metadata behind for us to parse. In the absence of that, we could sample the Z height and try to filter the fluctuations, but I feel like the time required to develop that would be better spent elsewhere. Sidenote:  Have you seen what happens in the Octoprint g-code viewer for vase modes?
