### ISSUE TITLE
Feature Request: Issue a notification when a print completes

### ISSUE THREAD

**Issue by kevinoliver** [prusa3d/Prusa-Link-Web#331]
It would be helpful to have an OS-level notification when a print completes.

**Comment by kevinoliver** [comment]
I'd be interested in contributing this if there is interest from the maintainers.

**Comment by mix579** [comment]
Great idea!

**Comment by Lowentwickler** [comment]
The feature is in our TODO list. Should be implemented soon enough.

**Comment by ondratu** [comment]
This functionality is in Connect, click on Bell icon next to your login avatar. Link have to stay simple.

**Comment by kevinoliver** [comment]
> This functionality is in Connect, click on Bell icon next to your login avatar. Link have to stay simple.

I'm not seeing this functionality in PrusaLink and this doesn't seem like it would make PrusaLink be "not simple". @ondratu can you explain a bit more?

**Comment by Prusa-Support** [comment]
_Prusa Link_ is the most **basic interface layer** between the printer and _Prusa Connect_.
_Prusa Connect_ will be the ultimate **printers manager platform**, capable of advanced features.
https://connect.prusa3d.com

Michele Moramarco
Prusa Research

**Comment by kevinoliver** [comment]
> _Prusa Link_ is the most **basic interface layer** between the printer and _Prusa Connect_. _Prusa Connect_ will be the ultimate **printers manager platform**, capable of advanced features. https://connect.prusa3d.com
> 
> Michele Moramarco Prusa Research

Michele Moramarco, thanks for explaining. 

I have a Mini+ and as far as I can tell _Prusa Connect_ does not support my printer. 😢

**Comment by Prusa-Support** [comment]
You are welcome.
No, the MINI is not supported by Prusa Connect, not now, not yet.
It is a matter of time though.

Michele Moramarco
Prusa Research
