### ISSUE TITLE
[FEATURE REQUEST] Show printer status on title of website

### ISSUE THREAD

**Issue by RyanDam** [prusa3d/Prusa-Link-Web#343]
One feature I'm missing from using Octoprint or Klipper Mainsail is showing printer status on the title of website. This feature is small but very convenient when you have multiple web browser tabs, and you can have a quick glance on tab to check print progress without opening the tab.

Beside showing printing progress, I think we could elevate this feature by showing more:
- "ready" when printer is idling
- "heating" when printer is heating up
- "xx%" when printer is printing
- "cooling down" when printer is finish printing and coolling down

**Comment by Lowentwickler** [comment]
Hi! Thank you for your request. I will discuss it with the team and let you know.
