### ISSUE TITLE
Wrong (different) font  on language dropdown

### ISSUE THREAD

**Issue by Gordontgopher** [prusa3d/Prusa-Link-Web#43]
![image](https://user-images.githubusercontent.com/3321366/104924395-43f41180-5995-11eb-97c1-d964fb77a75a.png)
It appears that the font on the drop down is different to the rest of the screen.

This is from a Mini running 4.3.0 RC2 firmware.

**Comment by Gordontgopher** [comment]
Where should this issue be logged now? I opened it against Prusa Connect, which has now been renamed to Prusa-Link-Web. Should I just not bother moving it to the correct repository as nobody has acknowledged it in 6 months?

**Comment by Gordontgopher** [comment]
@JohnnyDeer Is this in the wrong place or just being ignored due to higher priority on Mk3 PrusaConnect?

**Comment by ondratu** [comment]
This bug was fixed yet, and all printers will release bug fix (some was) in next public release.
