### ISSUE TITLE
[BUG] bootloader not updated when flashing firmware through Connect

### ISSUE THREAD

**Issue by ErGeeBee** [prusa3d/Prusa-Link-Web#466]
printer: mini+
fw: 5.1.0 and bootloader 2.3.0

Today I flashed 5.1.2 in the printer settings on connect.prusa3d.com
Flashing worked fine but the new bootloader didn’t get updated to 2.3.4.  Had to do it with usb after all.

**Comment by ondratu** [comment]
I'm not sure what you do with USB. But there are some issues in Buddy firmware and Buddy bootloader in your versions. Because, there is new firmware which you have to use with connect, which don't have this problems, i close this issue.
