### ISSUE TITLE
File explorer bgcode

### ISSUE THREAD

**Issue by Fluffybunny96** [prusa3d/Prusa-Link-Web#476]
When you upload a new file to the printer prusalink doesnt recognise the new file format BGCODE.

![image](https://github.com/prusa3d/Prusa-Link/assets/111734887/5d95fdc7-2723-40d0-b862-aa6e24fd717d)

To resolve this issue you cannot drag and drop bgcode, you have to browse to a file and then manually change file type to "All files"
![image](https://github.com/prusa3d/Prusa-Link/assets/111734887/0e597229-4962-4272-9aba-61eccb3f2cd5)

**Comment by TojikCZ** [comment]
Note: PrusaLink for MK3 won't support it, but yea, Buddy based printers should allow uploads of those

**Comment by ondratu** [comment]
This is duplicity for https://github.com/prusa3d/Prusa-Link-Web/pull/474#issuecomment-1891641230 Buddy printers are fixed yet.
