### ISSUE TITLE
[FEATURE REQUEST] Prusa Connect - Clear print history

### ISSUE THREAD

**Issue by Macronot** [prusa3d/Prusa-Link-Web#481]
Please add a clear print history option.

Possible options

- Clear ALL jobs
- Clear one job
- Clear jobs after a certain time period ( 30 days etc)

Thanks

**Comment by DACRY0N** [comment]
Hope they add this feature soon. I share my prusa with some family, and will be printing gifts shortly. I dont want them to see the history though so it can be a surprise. Really hope they add their delete print history option soon.

**Comment by ondratu** [comment]
Deployed to production.

![Snímek obrazovky z 2024-07-16 07-43-29](https://github.com/user-attachments/assets/95d34302-fa3e-4a5f-815e-a514e9dd6c20)

**Comment by pahdosam** [comment]
@ondratu This does not actually clear the history. Anything printed can still be seen in the notifications (which there is no way to clear, thus no way to hide things like gifts), and clicking on the notification takes you directly to the supposedly removed history page (which might be a fairness/transparency issue for data retention given that it says removal won't affect stats, but doesn't say that removal won't actually remove the data).
